# Annoying deprecation stuff
resolve-type-alias: False
disable-version-string: True
issue-845-fix: True

with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/saschagrunert/go-modiff/pkg/git:
    interfaces:
      Runner:
