// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// RunCmd provides a mock function with given fields: dir, cmd, args
func (_m *MockRunner) RunCmd(dir string, cmd string, args ...string) error {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, dir, cmd)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RunCmd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, ...string) error); ok {
		r0 = rf(dir, cmd, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRunner_RunCmd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCmd'
type MockRunner_RunCmd_Call struct {
	*mock.Call
}

// RunCmd is a helper method to define mock.On call
//   - dir string
//   - cmd string
//   - args ...string
func (_e *MockRunner_Expecter) RunCmd(dir interface{}, cmd interface{}, args ...interface{}) *MockRunner_RunCmd_Call {
	return &MockRunner_RunCmd_Call{Call: _e.mock.On("RunCmd",
		append([]interface{}{dir, cmd}, args...)...)}
}

func (_c *MockRunner_RunCmd_Call) Run(run func(dir string, cmd string, args ...string)) *MockRunner_RunCmd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockRunner_RunCmd_Call) Return(_a0 error) *MockRunner_RunCmd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRunner_RunCmd_Call) RunAndReturn(run func(string, string, ...string) error) *MockRunner_RunCmd_Call {
	_c.Call.Return(run)
	return _c
}

// RunCmdOutput provides a mock function with given fields: dir, cmd, args
func (_m *MockRunner) RunCmdOutput(dir string, cmd string, args ...string) ([]byte, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, dir, cmd)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RunCmdOutput")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, ...string) ([]byte, error)); ok {
		return rf(dir, cmd, args...)
	}
	if rf, ok := ret.Get(0).(func(string, string, ...string) []byte); ok {
		r0 = rf(dir, cmd, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, ...string) error); ok {
		r1 = rf(dir, cmd, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRunner_RunCmdOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCmdOutput'
type MockRunner_RunCmdOutput_Call struct {
	*mock.Call
}

// RunCmdOutput is a helper method to define mock.On call
//   - dir string
//   - cmd string
//   - args ...string
func (_e *MockRunner_Expecter) RunCmdOutput(dir interface{}, cmd interface{}, args ...interface{}) *MockRunner_RunCmdOutput_Call {
	return &MockRunner_RunCmdOutput_Call{Call: _e.mock.On("RunCmdOutput",
		append([]interface{}{dir, cmd}, args...)...)}
}

func (_c *MockRunner_RunCmdOutput_Call) Run(run func(dir string, cmd string, args ...string)) *MockRunner_RunCmdOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockRunner_RunCmdOutput_Call) Return(_a0 []byte, _a1 error) *MockRunner_RunCmdOutput_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRunner_RunCmdOutput_Call) RunAndReturn(run func(string, string, ...string) ([]byte, error)) *MockRunner_RunCmdOutput_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
