.nh
.TH go-modiff 8

.SH NAME
.PP
go-modiff - Command line tool for diffing go module dependency changes between versions


.SH SYNOPSIS
.PP
go-modiff

.PP
.RS

.nf
[--debug|-d]
[--from|-f]=[value]
[--header-level|-i]=[value]
[--help|-h]
[--include-empty|-e]
[--include-indirect|-I]
[--link|-l]
[--reference-clone]=[value]
[--repository|-r]=[value]
[--to|-t]=[value]
[--version|-v]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
Command line tool for diffing go module dependency changes between versions

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB--debug, -d\fP: enable debug output

.PP
\fB--from, -f\fP="": the start of the comparison, any valid git rev (default: "master")

.PP
\fB--header-level, -i\fP="": add a higher markdown header level depth (default: 1)

.PP
\fB--help, -h\fP: show help

.PP
\fB--include-empty, -e\fP: include empty added/changed/removed sections

.PP
\fB--include-indirect, -I\fP: include indirect imports

.PP
\fB--link, -l\fP: add diff links to the markdown output

.PP
\fB--reference-clone\fP="": path to an existing clone to use as the reference

.PP
\fB--repository, -r\fP="": repository to be used, like: github.com/owner/repo (defaults to the go module of the local git repository)

.PP
\fB--to, -t\fP="": the end of the comparison, any valid git rev (default: "master")

.PP
\fB--version, -v\fP: print the version


.SH COMMANDS
.SH docs, d
.PP
generate the markdown or man page documentation and print it to stdout

.PP
\fB--help, -h\fP: show help

.PP
\fB--man\fP: print the man version

.PP
\fB--markdown\fP: print the markdown version

.SS help, h
.PP
Shows a list of commands or help for one command

.SH fish, f
.PP
generate the fish shell completion and print it to stdout

.PP
\fB--help, -h\fP: show help

.SS help, h
.PP
Shows a list of commands or help for one command

.SH help, h
.PP
Shows a list of commands or help for one command
